// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYKJ9NsbwRLV4eS1u157iiq089Olgk-i4',
    appId: '1:662928781479:web:778b165232825cdcc62b82',
    messagingSenderId: '662928781479',
    projectId: 'lacasitadepapeldb',
    authDomain: 'lacasitadepapeldb.firebaseapp.com',
    storageBucket: 'lacasitadepapeldb.firebasestorage.app',
    measurementId: 'G-CWWKCRV4BN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3UQJo2SwvEx-9RIE5E2vV4apEsN3GORM',
    appId: '1:662928781479:android:7f279fa4d228da21c62b82',
    messagingSenderId: '662928781479',
    projectId: 'lacasitadepapeldb',
    storageBucket: 'lacasitadepapeldb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo-_sS-6RZTZCmrEi_5YCl4YTfnm9Y7aY',
    appId: '1:662928781479:ios:c4985e02f004d3d1c62b82',
    messagingSenderId: '662928781479',
    projectId: 'lacasitadepapeldb',
    storageBucket: 'lacasitadepapeldb.firebasestorage.app',
    iosBundleId: 'com.example.lacasitadepapel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo-_sS-6RZTZCmrEi_5YCl4YTfnm9Y7aY',
    appId: '1:662928781479:ios:c4985e02f004d3d1c62b82',
    messagingSenderId: '662928781479',
    projectId: 'lacasitadepapeldb',
    storageBucket: 'lacasitadepapeldb.firebasestorage.app',
    iosBundleId: 'com.example.lacasitadepapel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYKJ9NsbwRLV4eS1u157iiq089Olgk-i4',
    appId: '1:662928781479:web:d7f683844ddcf56bc62b82',
    messagingSenderId: '662928781479',
    projectId: 'lacasitadepapeldb',
    authDomain: 'lacasitadepapeldb.firebaseapp.com',
    storageBucket: 'lacasitadepapeldb.firebasestorage.app',
    measurementId: 'G-N95WKY0FC9',
  );
}
